services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # postgres:
  #  image: postgres:latest
  #  restart: unless-stopped
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data
  #  ports:
  #    - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
